language: go

go:
  - 1.8
  - 1.9

install:
  - go get -u github.com/golang/dep/...
  - dep ensure -v
  - go get github.com/mattn/goveralls
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - go test -v -race $(go list ./... | grep -v "/vendor/")
  - gometalinter --config=config.json ./...
  - goveralls -service=travis-ci
